import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/context/ThemeContext"

export const metadata: Metadata = {
  title: "Moments For Mother Earth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Toaster position="top-center" richColors />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
